package runtime

// The Docker naming scheme sucks..
// https://docs.docker.com/registry/introduction/#understanding-image-naming
type DockerImage struct {
	Tag        string
	Repository string
	Registry   string
}

type AppVersion string

type GivenVersion string

type ApplicationVersion struct {
	appVersion   AppVersion   // The actual version of the artifact. This will differ from GivenVersion iff the artifact
				  // is a snapshot artifact (the SNAPSHOT-part will be replaced with the timestamp generated by Nexus)
	Snapshot     bool         // If the artifact is a snapshot artifact. NPM has different semantics, so we are explicit
	givenVersion GivenVersion // The version set in the build config
}
